package pl.poznan.put.cs.si.puttalky
 
import pl.poznan.put.cs.si.puttalky.model.*;
import pl.poznan.put.cs.si.puttalky.BazaWiedzy;
import java.util.Set
import java.util.Arrays
import java.util.stream.Collectors;
import java.util.HashSet


rule "start"
	salience 4
	
	when
		not Fakt(nazwa=="start")
		zamowienie : Zamowienie()
	then
		zamowienie.powitanie();
		System.out.println();
		System.out.println();
		insert(new Fakt("start", "0"));
end

rule "zamowienie czy porada"
    salience 2

    when
        not Fakt(nazwa == "dodatek")
        not Fakt(nazwa == "ciasto")
        not Fakt(nazwa == "wybor")
        wybor: Wybor()
        parser: Parser()
    then
        wybor.setMonit("Czy chciałbyś zamówić pizzę, czy potrzebujesz porady?");
        wybor.zadajPytanie();
        parser.przetworzOdpowiedz();
        String res = wybor.parseAnswer(parser.getSlowaKluczowe());

        insert(new Fakt("wybor", res));
    end

rule "Podaj dodatki"
	salience 2
	
	when
		not Fakt(nazwa == "dodatek")
		Fakt(nazwa == "wybor", wartosc == Wybor.PORADA)
		dodatek : Dodatek()
		parser : Parser()
		baza : BazaWiedzy()
	then
		  dodatek.setMonit("Jaki dodatek powinna zawierać Twoja pizza?:\n");
		  dodatek.zadajPytanie();
		  parser.przetworzOdpowiedz();
		  for (String uri: baza.matchExtras(parser.getSlowaKluczowe())) {
		      System.out.println("dostałem " + uri);
		      insert(new Fakt("dodatek", uri));
		  }
        update(dodatek);
end

rule "Podaj rodzaj ciasta"
	salience 2
	
	when
		not Fakt(nazwa == "rodzaj_ciasta")
		Fakt(nazwa == "wybor", wartosc == Wybor.PORADA)
		ciasto : Ciasto()
		parser : Parser()
	then
		  ciasto.setMonit("Podaj rodzaj ciasta:\n");
		  ciasto.zadajPytanie();
		  parser.przetworzOdpowiedz();

		for (String slowo : parser.getSlowaKluczowe()){
			if (slowo.matches("cienk[ei]")){
		        insert(new Fakt("rodzaj_ciasta", "cienkie"));
			} else if (slowo.matches("grub[ye]")) {
		        insert(new Fakt("rodzaj_ciasta", "grube"));
			}
		}
        update(ciasto);
end

rule "Polecana pizza"
	salience 1
	
	when
		Fakt(nazwa == "dodatek", dodatek: wartosc)
		Fakt(nazwa == "rodzaj_ciasta", ciasto: wartosc)
		not Fakt(nazwa == "pizza_propozycja")
		baza: BazaWiedzy()
		pizza: Pizza()
		dodatki: HashSet() from collect( Fakt(nazwa == "dodatek"))
	then
		Set<String> pizze = baza.wyszukajPizzePoDodatkach(dodatki);
        if (pizze.size()>1){
			for (String nazwaPizzy : pizze) {
				insert(new Fakt("pizza_propozycja", nazwaPizzy));
		    	if (Pizza.isPizza(nazwaPizzy)){
		       	   System.out.println("Polecam pizzę:"+nazwaPizzy);
		       	}
		    }
		}
		else {
            Set<String> extras = baza.getMatchingExtrasNames(dodatek);
            if (extras.isEmpty()) {
                System.out.println("Nie mamy takiego dodatku");
            } else {
                System.out.println("Nie mamy pizzy zawierającej `" +
                    extras.iterator().next() +
                    "` jednak możemy ją wykonać na specjalne zamówienie"
                );
            }
	    }

end


rule "zloz zamowienie"
	salience 2

	when
		not Fakt(nazwa == "dodatek")
		Fakt(nazwa == "wybor", wartosc == Wybor.ZAMOWIENIE)
		dodatek : Dodatek()
		parser : Parser()
		baza : BazaWiedzy()
	then
		  dodatek.setMonit("Na jaką pizzę chciałbyś zgłosić zamówienie?\n");
		  dodatek.zadajPytanie();
		  parser.przetworzOdpowiedz();
		  String[] orderKeyWords = parser.getSlowaKluczowe();
		  Set<String> matched = baza.lookForPizzas(orderKeyWords);

		  for (String match: matched) {
		      System.out.println(match);
		  }

//		for (String slowo : parser.getSlowaKluczowe()){
//		    System.out.println("słowo " + slowo);
//			for (String uriKlasy : baza.dopasujDodatek(slowo)) {
//			    System.out.println("dopasowano :" + uriKlasy);
//		        insert(new Fakt("dodatek", uriKlasy));
//		    }
//		}
        update(dodatek);
end

rule "zakończenie"

	when
		not (Fakt(nazwa == "koniec"))
		Fakt(nazwa == "pizza_propozycja") 

		zamowienie : Zamowienie()
	then
		insert(new Fakt("koniec", "0"));
		zamowienie.pozegnanie();
end

