package pl.poznan.put.cs.si.puttalky
 
import pl.poznan.put.cs.si.puttalky.model.*;
import pl.poznan.put.cs.si.puttalky.BazaWiedzy;
import java.util.Set
import java.util.Arrays
import java.util.stream.Collectors;
import java.util.HashSet


rule "start"
	salience 3
	
	when
		not Fakt(nazwa=="start")
		zamowienie : Zamowienie()
	then
		zamowienie.powitanie();
		System.out.println();
		System.out.println();
		insert(new Fakt("start", "0"));
end

rule "Podaj dodatki lub zloz zamowienie"
	salience 2
	
	when
		not Fakt(nazwa == "dodatek" || nazwa == "bezDodatku" ||
		         nazwa == "zlecenie" || nazwa == "bezPizzy")
		dodatek : Dodatek()
		parser : Parser()
		baza : BazaWiedzy()
	then
		  dodatek.setMonit("Na jaką pizzę masz ochotę?:\n");
		  dodatek.zadajPytanie();
		  parser.przetworzOdpowiedz();
		  Sentence sentence = parser.getSentence();

		  for (String nazwa: baza.lookForPizzas(sentence.getWith())) {
		      insert(new Fakt("zlecenie", nazwa));
		  }

		  for (String nazwa: baza.lookForPizzas(sentence.getWithout())) {
              insert(new Fakt("bezPizzy", nazwa));
          }

		  for (String uri: baza.matchExtras(sentence.getWith())) {
		      insert(new Fakt("dodatek", uri));
		  }
		  for (String uri: baza.matchExtras(sentence.getWithout())) {
              insert(new Fakt("bezDodatku", uri));
          }
          update(dodatek);
end

rule "Podaj rodzaj ciasta"
	salience 2

	when
		not Fakt(nazwa == "rodzaj_ciasta")
		ciasto : Ciasto()
		parser : Parser()
	then
		  ciasto.setMonit("Podaj rodzaj ciasta:\n");
		  ciasto.zadajPytanie();
		  parser.przetworzOdpowiedz();

		for (String slowo : parser.getSentence().getWith()){
			if (slowo.matches("cienk[ei]")){
		        insert(new Fakt("rodzaj_ciasta", "cienkie"));
			} else if (slowo.matches("grub[ye]")) {
		        insert(new Fakt("rodzaj_ciasta", "grube"));
			}
		}
        update(ciasto);
end

rule "Polecana pizza"
	salience 1

	when
		Fakt(nazwa == "dodatek" || nazwa == "bezDodatku" ||
		     nazwa == "zlecenie" || nazwa == "bezPizzy")
		not Fakt(nazwa == "pizza_propozycja")
		Fakt(nazwa == "rodzaj_ciasta")
		baza: BazaWiedzy()
		pizza: Pizza()
		dodatki: HashSet() from collect( Fakt(nazwa == "dodatek"))
		bezDodatku: HashSet() from collect( Fakt(nazwa == "bezDodatku"))
		zlecenie: HashSet() from collect( Fakt(nazwa == "zlecenie"))
		bezPizz: HashSet() from collect( Fakt(nazwa == "bezPizzy"))
	then
		Set<String> pizze = baza.lookForPizzasByExtras(dodatki, bezDodatku, zlecenie, bezPizz);
        if (!pizze.isEmpty()) {
			for (String nazwaPizzy : pizze) {
				insert(new Fakt("pizza_propozycja", nazwaPizzy));
		    	if (Pizza.isPizza(nazwaPizzy)){
		       	   System.out.println("Polecam pizzę:"+nazwaPizzy);
		       	}
		    }
		}
		else {
            System.out.println("Nie mamy w ofercie pizzy złożonej z " + dodatki.stream().map(s -> ((Fakt)s).getWartosc()).collect(Collectors.toList()));
            dodatki.forEach(d -> retract(d));
            bezDodatku.forEach(d -> retract(d));
            zlecenie.forEach(d -> retract(d));
            bezPizz.forEach(d -> retract(d));
	    }

end

rule "zakończenie"

	when
		not (Fakt(nazwa == "koniec"))
		Fakt(nazwa == "pizza_propozycja") 

		zamowienie : Zamowienie()
	then
		insert(new Fakt("koniec", "0"));
		zamowienie.pozegnanie();
end

